### ISSUE TITLE
Test adding `wordpress/env` for local development

### ISSUE THREAD

**Issue by brylie** [creativecommons/wp-plugin-creativecommons#185]
The Gutenberg team have published `@wordpress/env` as a tool for simplifying WordPress development environments. However, we have tried the `@wordpress/env` project in `project_creativecommons.org` and were bitten by some complexities as well as determining it wasn't a good fit for the project.

That said, the `wp-plugin-creativecommons` project may be a better candidate for using `@wordpress/env`.

## Task

- [ ] install `@wordpress/env` as a development dependency of this project
- [ ] add the `wp-env` command to our `package.json`
- [ ] update the developer documentation to mention how to use `wp-env` for development
- [ ] ensure that `wp-env` works for both the PHP code **and** Gutenberg block development in this project

## Resources

- [@wordpress/env](https://www.npmjs.com/package/@wordpress/env) project page at NPM

**Comment by cillacode** [comment]
yes i can do that
