### ISSUE TITLE
Warning: getimagesize: failed to open stream

### ISSUE THREAD

**Issue by brylie** [creativecommons/wp-plugin-creativecommons#187]
When installing this plugin in a local WordPress 5.8 development environment, the following error is displayed when rendering the license:

> Warning: getimagesize(http://localhost:8888/wp-content/plugins/wp-plugin-creativecommons/includes/images/by.png): failed to open stream: Cannot assign requested address in /var/www/html/wp-content/plugins/wp-plugin-creativecommons/includes/class-creativecommons.php on line 1128 

## Steps to reproduce

1. set up WordPress 5.8 (locally or on a server) in development mode
2. install the latest version of the code from this repository in the WordPress plugins directory
3. Go to Settings -> Creative Commons
4. configure the desired license
5. make sure to select "Display license as:" "widget" 
6. go to Appearance -> Widgets
7. add a "Legacy Widget" and select "CC License" widget
8. save the widget settings
9. view the site and notice the Warning in the widget area

## Task
- [ ] reproduce the issue as described above
- [ ] determine the severity of the notices 
- [ ] if needed, fix fhe issue so the notices no longer display

**Comment by mimi-tech** [comment]
Hi , I am an Outreachy candidate. I will like to work on this issue. Thank you.

**Comment by brylie** [comment]
@mimi-tech, thanks! I'll assign you to the issue.

**Comment by mimi-tech** [comment]
@brylie, Alright, thanks so much

**Comment by mimi-tech** [comment]
Alright, thanks a lot.

**Comment by mimi-tech** [comment]
@BjornW , These are the errors I am getting. It is different from the error mentioned above. Please can you explain to me how to solve the error or is it from the way I installed the plugin.
Thank you.


[13-Oct-2021 18:58:04 UTC] called site
[13-Oct-2021 18:58:04 UTC] single site, get site license or else default settings
[13-Oct-2021 18:58:04 UTC] get license for the frontend
[13-Oct-2021 18:58:04 UTC] called site
[13-Oct-2021 18:58:04 UTC] single site, get site license or else default settings
[13-Oct-2021 18:58:04 UTC] called site
[13-Oct-2021 18:58:04 UTC] single site, get site license or else default settings
[13-Oct-2021 18:59:41 UTC] called site
[13-Oct-2021 18:59:41 UTC] single site, get site license or else default settings
[13-Oct-2021 18:59:41 UTC] get license for the frontend
[13-Oct-2021 18:59:41 UTC] called site
[13-Oct-2021 18:59:41 UTC] single site, get site license or else default settings
[13-Oct-2021 18:59:41 UTC] called site
[13-Oct-2021 18:59:41 UTC] single site, get site license or else default settings
[13-Oct-2021 19:05:51 UTC] called site
[13-Oct-2021 19:05:51 UTC] single site, get site license or else default settings
[13-Oct-2021 19:05:51 UTC] get license for the frontend
[13-Oct-2021 19:05:51 UTC] called site
[13-Oct-2021 19:05:51 UTC] single site, get site license or else default settings
[13-Oct-2021 19:05:51 UTC] called site
[13-Oct-2021 19:05:51 UTC] single site, get site license or else default settings
[13-Oct-2021 19:12:50 UTC] called site
[13-Oct-2021 19:12:50 UTC] single site, get site license or else default settings
[13-Oct-2021 19:12:50 UTC] get license for the frontend
[13-Oct-2021 19:12:50 UTC] called site
[13-Oct-2021 19:12:50 UTC] single site, get site license or else default settings
[13-Oct-2021 19:12:50 UTC] called site
[13-Oct-2021 19:12:50 UTC] single site, get site license or else default settings

**Comment by Vickyaryan33** [comment]
I want to work on this issues please assign me this issues @ [brylie](https://github.com/brylie)

**Comment by MrMK0R** [comment]
Hey there!

I have found a fix, however this is my first git issue I've worked. I would really appreciate some help to get things flowing.

Thanks!

**Comment by ArchanRD** [comment]
Hey I was checking out this issue. But I could not see "Legacy widgets" listed in Appearance->Widgets.

**Comment by ArchanRD** [comment]
Hey @brylie, I tried to reproduce the issue, but the widget works completely fine on the latest plugin code.

![image](https://github.com/creativecommons/wp-plugin-creativecommons/assets/74826173/a5e03299-71cd-4f5c-9943-0e0e763955cf)

**Comment by ArchanRD** [comment]
@possumbilities @brylie I've created a PR for this issue. Please check it out!
